"""initial schema: accounts, securities, trades, alerts, graph snapshots

Revision ID: bdad83921731
Revises: 
Create Date: 2026-09-10 15:30:16.143349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bdad83921731'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('external_ref', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('account_type', sa.Enum('retail', 'institutional', 'hedge_fund', 'market_maker', 'prop_desk', name='account_type'), nullable=False),
    sa.Column('risk_tier', sa.Enum('low', 'medium', 'high', name='risk_tier'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_ref')
    )
    op.create_table('graph_snapshots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_label', sa.String(length=16), nullable=False),
    sa.Column('num_nodes', sa.Integer(), nullable=False),
    sa.Column('num_edges', sa.Integer(), nullable=False),
    sa.Column('num_communities', sa.Integer(), nullable=False),
    sa.Column('modularity', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_graph_snapshots_window', 'graph_snapshots', ['window_start', 'window_end'], unique=False)
    op.create_table('securities',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=False),
    sa.Column('liquidity_tier', sa.Enum('liquid', 'mid', 'illiquid', name='liquidity_tier'), nullable=False),
    sa.Column('adv', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('reference_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('graph_community_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('snapshot_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.Enum('community_formed', 'community_dissolved', 'density_spike', 'new_pair', name='community_event_type'), nullable=False),
    sa.Column('community_key', sa.String(length=64), nullable=False),
    sa.Column('member_account_ids', postgresql.ARRAY(sa.BigInteger()), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['graph_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('external_id', sa.String(length=48), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('security_id', sa.BigInteger(), nullable=False),
    sa.Column('side', sa.Enum('buy', 'sell', name='side'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('notional', sa.Numeric(precision=28, scale=6), sa.Computed('quantity * price', persisted=True), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('venue', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('counterparty_account_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['counterparty_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('ix_trades_account_executed', 'trades', ['account_id', 'executed_at'], unique=False)
    op.create_index('ix_trades_executed_at', 'trades', ['executed_at'], unique=False)
    op.create_index('ix_trades_security_executed', 'trades', ['security_id', 'executed_at'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dedup_key', sa.String(length=160), nullable=False),
    sa.Column('alert_type', sa.Enum('statistical_outlier', 'wash_trade_ring', 'coordinated_cluster', name='alert_type'), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='severity'), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('detection_method', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('open', 'cleared', 'escalated', name='alert_status'), nullable=False),
    sa.Column('primary_trade_id', sa.BigInteger(), nullable=True),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['primary_trade_id'], ['trades.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key', name='uq_alerts_dedup_key')
    )
    op.create_index('ix_alerts_created_at', 'alerts', ['created_at'], unique=False)
    op.create_index('ix_alerts_type_status', 'alerts', ['alert_type', 'status'], unique=False)
    op.create_table('alert_accounts',
    sa.Column('alert_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alert_id', 'account_id')
    )
    op.create_table('alert_trades',
    sa.Column('alert_id', sa.BigInteger(), nullable=False),
    sa.Column('trade_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alert_id', 'trade_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_trades')
    op.drop_table('alert_accounts')
    op.drop_index('ix_alerts_type_status', table_name='alerts')
    op.drop_index('ix_alerts_created_at', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_trades_security_executed', table_name='trades')
    op.drop_index('ix_trades_executed_at', table_name='trades')
    op.drop_index('ix_trades_account_executed', table_name='trades')
    op.drop_table('trades')
    op.drop_table('graph_community_events')
    op.drop_table('securities')
    op.drop_index('ix_graph_snapshots_window', table_name='graph_snapshots')
    op.drop_table('graph_snapshots')
    op.drop_table('accounts')
    # ### end Alembic commands ###
